Merge branch 'chore/fix-build-3' - fix dynamic import
Squashed commit of the following:

commit 79b8c56b28fc34b0f4c6be3c66f5d4edf4255b32
Author: Jacopo Marrone <jacopo.marrone27@gmail.com>
Date:   Tue Jul 29 00:57:34 2025 +0200

    refactor: move code

commit 6c5bfac24d10f5221edbf0a2eee97ad70adae3b7
Author: Jacopo Marrone <jacopo.marrone27@gmail.com>
Date:   Tue Jul 29 00:57:07 2025 +0200

    chore: fix `Type error: Cannot find module` in build
    Even if `APP_DATA_MODE` is `compute`, the if branch for `static` is statically checked BEFORE the build.
    This trigger error:
    `Type error: Cannot find module '#root/registry/output/static-registry.for-next-app.json' or its corresponding type declarations.`

    Webpack/Turbopack, before the build process, statically anaylze every import, also dynamic `import()`, and :
    - IF THE PATH IS A SINGLE STRING, like `'path/to/file'`, it check if file exists
    - IF THE PATH IS A CONCAT STRING, like `'path/to' + 'file'`, it skips the check

    We change the path, splitting the string into two parts, with a `+` for concat.
    This way Webpack/Turbpack skip it.